baseURL: "https://konanok.github.io"
title: "è¿·å®®ã®åå­—è·¯"

languageCode: zh
defaultContentLanguage: zh
defaultContentLanguageInSubdir: true

theme: "my-hugo-PaperMod"
paginate: 7
enableInlineShortcodes: true
enableRobotsTXT: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "konanok's blog"
  author: konanok
  ShowShareButtons: false
  ShowReadingTime: true
  defaultTheme: auto
  displayFullLangName: true

  homeInfoParams:
    Title: "æ¬¢è¿å›æ¥ğŸ‘"
    Content: >
      Welcome to demo of hugo's theme PaperMod.
      - **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.
  socialIcons:
    - name: github
      url: "https://github.com/adityatelange/hugo-PaperMod"
    - name: email
      url: "mailto:konanok@outlook.com"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - name: å½’æ¡£
      url: /archives/
      weight: 10
    - name: åˆ†ç±»
      url: /categories/
      weight: 20
    - name: æ ‡ç­¾
      url: /tags/
      weight: 30
    - name: æœç´¢
      url: /search/
      weight: 40
    - name: å…³äº
      url: /about/
      weight: 50
